spring.application.name=BackendCinema
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update

logging.level.com.zaxxer.hikari=DEBUG

# Logowanie prób po??czenia na poziomie sterownika JDBC
logging.level.org.postgresql=DEBUG